name: Helm Lint
on: push
env:
  HELM_HELPER: ${{ secrets.HELM_HELPER_IMAGE }}
jobs:
  lint:
    runs-on: [helm-deploy]
    steps:
      - run: docker login -u ${{ secrets.DOCKER_REGISTRY_USER }} -p ${{ secrets.DOCKER_REGISTRY_PASSWORD }} "${{ secrets.HELM_HELPER_IMAGE }}"
      - name: Lint
        run: docker run ${{ env.HELM_HELPER }} helm lint ./landing